name: Tawheed TIPS Learning

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      ClassPath:
        description: 'Class Path  Eg: com/tawheed/assignment' # please provide class path. eg: com/tawheed/assignment
        default: ''
        required: true

      ClassName:
        description: 'Class Name without extention' # please provide class name without extention.
        default: ''
        required: true
        
env:
  CLASS_PATH: ${{ github.event.inputs.ClassPath }}
  CLASS_NAME: ${{ github.event.inputs.ClassName }}

jobs:
  Run-Java-Program:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '11'
          
      - name: Compile & Run class ${{ env.CLASS_NAME }}
        run: | 
          cd src/${{ env.CLASS_PATH }}
          javac ${{ env.CLASS_NAME }}".java"
          java ${{ env.CLASS_NAME }}".java"

